---
# tasks file for nginxwatcher

- name: Create nginxwatcher.path systemd unit from template
  template:
    src: nginxwatcher.path.j2
    dest: /etc/systemd/system/nginxwatcher.path
                
- name: Create nginxwatcher.service systemd unit from template
  template:
    src: nginxwatcher.service.j2
    dest: /etc/systemd/system/nginxwatcher.service
                
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable nginxwatcher.service systemd unit
  systemd:
    name: nginxwatcher.service
    enabled: yes

- name: Enable and start nginxwatcher.path systemd unit
  systemd:
    name: nginxwatcher.path
    state: started
    enabled: yes

